FROM python:3.11-slim

#setting ENV vars
ENV PYTHONBUFFERED=1\ ENV = "prod"

WORKDIR /app

#install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Copy app code 
COPY . .

#Exposing fast api default port
EXPOSE 8000

#Run with uvicorn
CMD [ "uvicorn","main:app","--host","0.0.0.0","--port","8000" ]

